export const BLOGS_PATHS ='/blogs'
export const POST_PATHS ='/posts'
export const TESTING_PATHS ='/testing'
export const AUTH_PATHS ='/auth'
export const USER_PATHS ='/users'
export const COMMENT_PATHS ='/comments'
export const SECURITY_PATHS ='/security'